name: GitHub Output
on: [push]

jobs:
  io:
    runs-on: ubuntu-latest
    steps:
      - id: set-var
      - name: hello
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f'VAL=true', file=f)
        shell: python
      - name: print value of magic command
#         if: steps.get-magic-value.outcome == 'success' && steps.get-magic-value.output.VAL == 'true'
        run: echo "the value is $${{ steps.set-var.output.VAL }}"
